name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: docker build . -t openclip

      - name: Test
        run: docker run -v $PWD/data_1:/data --env output_file=None --env extent=None -t openclip

      - name: Test - save log file
        run: docker run -v $PWD/data:/data --env output_file=None --env extent=616000,304000,627000,315000 --env save_logfile=True -t openclip

      - name: Test - clip raster to vector outline rather than bounding box
        run: docker run -v $PWD/data_3:/data --env output_file=None --env extent=None --env clip_to_extent_bbox=clip-to-vector-outline -t openclip
