name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: docker build . -t clip

      - name: Test
        run: docker run -v $PWD/data:/data --env data_type=raster --env output_file=None --env extent=None -t clip
