name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test raster clip
        run: docker build . -t clip && docker run --env data_type=raster -t clip
